[package]
name = "ultimate-desktop-reflector"
version = "0.1.0"
authors = ["Isamu Mogi <isamu@leafytree.jp>"]
edition = "2018"
build = "build.rs"

[dependencies]

[build-dependencies]
bindgen = "*"
pkg-config = "*"
